# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'

    - name: Setup venv
      run: |
        python -m venv venv
        . .\venv\Scripts\activate.ps1
        pip install -r requirements.txt
    - name: Build
      run: |
        . .\venv\Scripts\activate.ps1
        fbs freeze
        Compress-Archive -Path "target\PyChan" -DestinationPath pychan-win.zip
    - uses: actions/upload-artifact@v1
      with:
        name: PyChan
        path: pychan-win.zip
